CREATE TABLE artists (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE artist_urls (
    id BIGSERIAL PRIMARY KEY,
    artist_id BIGINT REFERENCES artists(id) ON DELETE CASCADE,
    url TEXT NOT NULL UNIQUE
);
