services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres
    restart: unless-stopped
    networks:
      - api
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USR}
      POSTGRES_PASSWORD: ${DB_PSWD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./api/db:/docker-entrypoint-initdb.d
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - api
      - web
    ports:
      - "80:80"
    environment:
      - NGINX_ENVSUBST_FILTER=VITE_API_HOST|VITE_API_PORT|VITE_WEB_PORT|IMG_PATH|PREVIEW_PATH|VIDEO_PATH
    volumes:
    - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    - ./nginx/conf.d/cors.conf:/etc/nginx/snippets/cors.conf:ro
    - ./nginx/conf.d/websocket.conf:/etc/nginx/snippets/websocket.conf:ro
    - ./nginx/init-permissions.sh:/docker-entrypoint.d/30-permissions.sh:ro
    - ${IMG_PATH}:${IMG_PATH}
    - ${PREVIEW_PATH}:${PREVIEW_PATH}
    - ${VIDEO_PATH}:${VIDEO_PATH}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: pnpm -F api dev
    env_file:
      - .env
    networks:
      - api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/api/node_modules
      - /app/web/node_modules
      - ${IMG_PATH}:${IMG_PATH}
      - ${PREVIEW_PATH}:${PREVIEW_PATH}
      - ${VIDEO_PATH}:${VIDEO_PATH}
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: pnpm -F web dev
    env_file:
      - .env
    networks:
      - web
    volumes:
      - .:/app
      - /app/node_modules
      - /app/api/node_modules
      - /app/web/node_modules
networks:
  api:
  web:

volumes:
  postgres:
